-- Create the slang table if it doesn't exist
CREATE TABLE IF NOT EXISTS slang (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    abbr TEXT UNIQUE NOT NULL,
    full_name TEXT NOT NULL
);

-- Clear existing data if you want a fresh start (optional, uncomment if needed)
-- DELETE FROM slang;

-- Insert all abbreviations and slang terms
INSERT OR REPLACE INTO slang (abbr, full_name) VALUES
('AK', 'Ahn''kahet: The Old Kingdom'),
('AN', 'Azjol-Nerub'),
('AoE', 'area of effect'),
('AQ20', 'Ruins of Ahn''Qiraj'),
('AQ40', 'Temple of Ahn''Qiraj'),
('Barrens', 'The Barrens'),
('BB', 'Booty Bay'),
('BF', 'Blood Furnace'),
('BFD', 'Blackfathom Deeps'),
('BIS', 'best in slot'),
('BM', 'Black Morass'),
('BM hunter', 'Beast Mastery Hunter'),
('Boomkin', 'balance druid'),
('BRD', 'Blackrock Depths'),
('BT', 'Black Temple'),
('BWL', 'Blackwing Lair'),
('CC', 'crowd control'),
('CD', 'cooldown'),
('CoS', 'The Culling of Stratholme'),
('Crypts', 'Auchenai Crypts'),
('Dal', 'Dalaran'),
('Destro', 'destruction warlock'),
('Disc', 'discipline priest'),
('DK', 'death knight'),
('DM', 'Dire Maul'),
('DoT', 'Damage over time'),
('DTK', 'Drak''Tharon Keep'),
('EDK', 'Escape from Durnholde Keep'),
('EoE', 'Eye of Eternity'),
('EPL', 'Eastern Plaguelands'),
('FoS', 'Forge of Souls'),
('GCD', 'global cooldown'),
('GD', 'Gundrak'),
('Gruul', 'Gruul''s Lair'),
('Hinterlands', 'The Hinterlands'),
('HoL', 'Halls of Lightning'),
('HoR', 'Halls of Reflection'),
('HoS', 'Halls of Stone'),
('HoT', 'Heal over time'),
('HR', 'Hellfire Ramparts'),
('Hyjal', 'Battle for Mount Hyjal'),
('ICC', 'Icecrown Citadel'),
('IF', 'Ironforge'),
('Kara', 'Karazhan'),
('LBRS', 'Lower Blackrock Spire'),
('LFG', 'looking for group'),
('LFM', 'looking for more players'),
('LFR', 'looking for raid'),
('LOS', 'line of sight'),
('Mara', 'Maraudon'),
('MC', 'Molten Core'),
('MM', 'marksmanship hunter'),
('MS', 'main spec'),
('MT', 'Magisters'' Terrace'),
('MTL', 'Magtheridon''s Lair'),
('Naxx', 'Naxxramas'),
('Nexus', 'The Nexus'),
('Oculus', 'The Oculus'),
('Ony', 'Onyxia''s Lair'),
('OOM', 'out of mana'),
('Org', 'Orgrimmar'),
('OS', 'off spec'),
('Pally', 'paladin'),
('PoS', 'Pit of Saron'),
('Prot', 'protection'),
('Res', 'resurrect'),
('Ret', 'retribution'),
('Retardin', 'retribution paladin'),
('Resto', 'restoration'),
('RFC', 'Ragefire Chasm'),
('RFD', 'Razorfen Downs'),
('RFK', 'Razorfen Kraul'),
('RNG', 'random'),
('Sanctum', 'Obsidian Sanctum'),
('Scholo', 'Scholomance'),
('SH', 'Sethekk Halls'),
('Shat', 'Shattrath'),
('Sholazar', 'Sholazar Basin'),
('SHalls', 'Shattered Halls'),
('SFK', 'Shadowfang Keep'),
('SLab', 'Shadow Labyrinth'),
('SM', 'Scarlet Monastery'),
('SM Armory', 'Scarlet Monastery Armory'),
('SM Cath', 'Scarlet Monastery Cathedral'),
('SM GY', 'Scarlet Monastery Graveyard'),
('SM Library', 'Scarlet Monastery Library'),
('SoS', 'Swamp of Sorrows'),
('SP', 'Slave Pens'),
('SSC', 'Serpentshrine Cavern'),
('ST', 'Temple of Atal''Hakkar (Sunken Temple)'),
('Stockades', 'Stormwind Stockade'),
('Strath', 'Stratholme'),
('STV', 'Stranglethorn Vale'),
('SV', 'Steamvault'),
('SW', 'Stormwind'),
('SWP', 'Sunwell Plateau'),
('TB', 'Thunder Bluff'),
('TK', 'The Eye (Tempest Keep)'),
('ToC', 'Trial of the Crusader'),
('Tombs', 'Mana-Tombs'),
('Trial Champ', 'Trial of the Champion'),
('UBRS', 'Upper Blackrock Spire'),
('UC', 'Undercity'),
('UK', 'Utgarde Keep'),
('Un''Goro', 'Un''Goro Crater'),
('UP', 'Utgarde Pinnacle'),
('VC', 'Deadmines'),
('VH', 'Violet Hold'),
('VoA', 'Vault of Archavon'),
('WC', 'Wailing Caverns'),
('WG', 'Wintergrasp'),
('WPL', 'Western Plaguelands'),
('WTB', 'want to buy'),
('WTT', 'want to trade'),
('WTS', 'want to sell'),
('ZA', 'Zul''Aman'),
('ZD', 'Zul''Drak'),
('ZF', 'Zul''Farrak'),
('ZG', 'Zul''Gurub'),
('FP', 'flight path'),
('FM', 'flight master'),
('WSG', 'Warsong Gulch'),
('AB', 'Arathi Basin'),
('AV', 'Alterac Valley');